### ISSUE TITLE
first observations

### ISSUE THREAD

**Issue by koo5** [oldm/OldMan#41] opened 2015-02-14 18:00 UTC
first of all, i wish this library much success.

http://oldman.readthedocs.org/en/latest/quickstart.html is a tad outdated. client_manager.use_all_store_models() is now client_manager.import_store_models()

earlier, if youre reading the pdf version, the cut off line should be
context_iri = "https://raw.githubusercontent.com/oldm/OldMan/master/examples/quickstart_context.jsonld"

even earlier, youre gonna run into something like this:
```
In [2]: from oldman import ClientResourceManager, parse_graph_safely, SPARQLDataStore
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-3c41177edc7c> in <module>()
----> 1 from oldman import ClientResourceManager, parse_graph_safely, SPARQLDataStore

/home/kook/envs/oldman-2.7/build/bdist.linux-x86_64/egg/oldman/__init__.py in <module>()

/home/kook/envs/oldman-2.7/build/bdist.linux-x86_64/egg/oldman/resource/manager.py in <module>()

ImportError: No module named store.selector
```
im not sure what the solution was exactly, but i think removing the notion of oldman from site-packages and importing it from its directory directly.

**Comment by bcogrel** [comment] 2015-02-17 21:09
Hi koo5, 

Thanks a lot for your feedback!
I have committed your changes and I have tested the quick start, should be up-to-date now.

However, I have not been able to reproduce your problem on my GNU/Linux. From your log, I suppose that you have followed http://oldman.readthedocs.org/en/latest/installation.html . 

Are you using Python 2.7?
Are you sure oldman is not installed in your global site-packages?

**Comment by koo5** [comment] 2015-02-21 01:05
yes thats the procedure that i tried to follow, but who knows what i actually did:)
hope this helps:
```
(oldman-2.7)kook@kook-ThinkPad-R61e:~/envs/oldman-2.7/src/oldman$ git show -q HEAD
commit 79ef17bbdee22ec25f5eb76e7affacdcf8ae14d9
Author: Benjamin Cogrel <benjamin.cogrel@bcgl.fr>
Date:   Tue Feb 17 21:43:43 2015 +0100

    Typos found by koo5 (#41).
(oldman-2.7)kook@kook-ThinkPad-R61e:~/envs/oldman-2.7/src/oldman$ python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to OldMan.egg-info/requires.txt
writing OldMan.egg-info/PKG-INFO
writing top-level names to OldMan.egg-info/top_level.txt
writing dependency_links to OldMan.egg-info/dependency_links.txt
reading manifest file 'OldMan.egg-info/SOURCES.txt'
writing manifest file 'OldMan.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/oldman
copying build/lib.linux-x86_64-2.7/oldman/__init__.py -> build/bdist.linux-x86_64/egg/oldman
copying build/lib.linux-x86_64-2.7/oldman/common.py -> build/bdist.linux-x86_64/egg/oldman
copying build/lib.linux-x86_64-2.7/oldman/exception.py -> build/bdist.linux-x86_64/egg/oldman
copying build/lib.linux-x86_64-2.7/oldman/iri.py -> build/bdist.linux-x86_64/egg/oldman
copying build/lib.linux-x86_64-2.7/oldman/vocabulary.py -> build/bdist.linux-x86_64/egg/oldman
creating build/bdist.linux-x86_64/egg/oldman/model
copying build/lib.linux-x86_64-2.7/oldman/model/__init__.py -> build/bdist.linux-x86_64/egg/oldman/model
copying build/lib.linux-x86_64-2.7/oldman/model/ancestry.py -> build/bdist.linux-x86_64/egg/oldman/model
copying build/lib.linux-x86_64-2.7/oldman/model/attribute.py -> build/bdist.linux-x86_64/egg/oldman/model
copying build/lib.linux-x86_64-2.7/oldman/model/converter.py -> build/bdist.linux-x86_64/egg/oldman/model
copying build/lib.linux-x86_64-2.7/oldman/model/manager.py -> build/bdist.linux-x86_64/egg/oldman/model
copying build/lib.linux-x86_64-2.7/oldman/model/model.py -> build/bdist.linux-x86_64/egg/oldman/model
copying build/lib.linux-x86_64-2.7/oldman/model/operation.py -> build/bdist.linux-x86_64/egg/oldman/model
copying build/lib.linux-x86_64-2.7/oldman/model/property.py -> build/bdist.linux-x86_64/egg/oldman/model
copying build/lib.linux-x86_64-2.7/oldman/model/registry.py -> build/bdist.linux-x86_64/egg/oldman/model
creating build/bdist.linux-x86_64/egg/oldman/resource
copying build/lib.linux-x86_64-2.7/oldman/resource/__init__.py -> build/bdist.linux-x86_64/egg/oldman/resource
copying build/lib.linux-x86_64-2.7/oldman/resource/manager.py -> build/bdist.linux-x86_64/egg/oldman/resource
copying build/lib.linux-x86_64-2.7/oldman/resource/resource.py -> build/bdist.linux-x86_64/egg/oldman/resource
creating build/bdist.linux-x86_64/egg/oldman/parsing
copying build/lib.linux-x86_64-2.7/oldman/parsing/__init__.py -> build/bdist.linux-x86_64/egg/oldman/parsing
copying build/lib.linux-x86_64-2.7/oldman/parsing/operation.py -> build/bdist.linux-x86_64/egg/oldman/parsing
copying build/lib.linux-x86_64-2.7/oldman/parsing/value.py -> build/bdist.linux-x86_64/egg/oldman/parsing
creating build/bdist.linux-x86_64/egg/oldman/parsing/schema
copying build/lib.linux-x86_64-2.7/oldman/parsing/schema/__init__.py -> build/bdist.linux-x86_64/egg/oldman/parsing/schema
copying build/lib.linux-x86_64-2.7/oldman/parsing/schema/attribute.py -> build/bdist.linux-x86_64/egg/oldman/parsing/schema
copying build/lib.linux-x86_64-2.7/oldman/parsing/schema/context.py -> build/bdist.linux-x86_64/egg/oldman/parsing/schema
copying build/lib.linux-x86_64-2.7/oldman/parsing/schema/property.py -> build/bdist.linux-x86_64/egg/oldman/parsing/schema
creating build/bdist.linux-x86_64/egg/oldman/rest
copying build/lib.linux-x86_64-2.7/oldman/rest/__init__.py -> build/bdist.linux-x86_64/egg/oldman/rest
copying build/lib.linux-x86_64-2.7/oldman/rest/controller.py -> build/bdist.linux-x86_64/egg/oldman/rest
copying build/lib.linux-x86_64-2.7/oldman/rest/crud.py -> build/bdist.linux-x86_64/egg/oldman/rest
creating build/bdist.linux-x86_64/egg/oldman/utils
copying build/lib.linux-x86_64-2.7/oldman/utils/__init__.py -> build/bdist.linux-x86_64/egg/oldman/utils
copying build/lib.linux-x86_64-2.7/oldman/utils/crud.py -> build/bdist.linux-x86_64/egg/oldman/utils
copying build/lib.linux-x86_64-2.7/oldman/utils/sparql.py -> build/bdist.linux-x86_64/egg/oldman/utils
creating build/bdist.linux-x86_64/egg/oldman/validation
copying build/lib.linux-x86_64-2.7/oldman/validation/__init__.py -> build/bdist.linux-x86_64/egg/oldman/validation
copying build/lib.linux-x86_64-2.7/oldman/validation/value_format.py -> build/bdist.linux-x86_64/egg/oldman/validation
byte-compiling build/bdist.linux-x86_64/egg/oldman/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/common.py to common.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/exception.py to exception.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/iri.py to iri.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/vocabulary.py to vocabulary.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/model/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/model/ancestry.py to ancestry.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/model/attribute.py to attribute.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/model/converter.py to converter.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/model/manager.py to manager.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/model/model.py to model.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/model/operation.py to operation.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/model/property.py to property.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/model/registry.py to registry.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/resource/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/resource/manager.py to manager.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/resource/resource.py to resource.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/parsing/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/parsing/operation.py to operation.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/parsing/value.py to value.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/parsing/schema/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/parsing/schema/attribute.py to attribute.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/parsing/schema/context.py to context.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/parsing/schema/property.py to property.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/rest/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/rest/controller.py to controller.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/rest/crud.py to crud.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/utils/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/utils/crud.py to crud.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/utils/sparql.py to sparql.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/validation/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/oldman/validation/value_format.py to value_format.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying OldMan.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying OldMan.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying OldMan.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying OldMan.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying OldMan.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/OldMan-0.2-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing OldMan-0.2-py2.7.egg
Copying OldMan-0.2-py2.7.egg to /home/kook/envs/oldman-2.7/lib/python2.7/site-packages
Adding OldMan 0.2 to easy-install.pth file

Installed /home/kook/envs/oldman-2.7/lib/python2.7/site-packages/OldMan-0.2-py2.7.egg
Processing dependencies for OldMan==0.2
Searching for negotiator==1.0.0
Best match: negotiator 1.0.0
Adding negotiator 1.0.0 to easy-install.pth file

Using /home/kook/envs/oldman-2.7/lib/python2.7/site-packages
Searching for requests==2.5.1
Best match: requests 2.5.1
Adding requests 2.5.1 to easy-install.pth file

Using /home/kook/envs/oldman-2.7/lib/python2.7/site-packages
Searching for dogpile.cache==0.5.6
Best match: dogpile.cache 0.5.6
Adding dogpile.cache 0.5.6 to easy-install.pth file

Using /home/kook/envs/oldman-2.7/lib/python2.7/site-packages
Searching for validate-email==1.2
Best match: validate-email 1.2
Adding validate-email 1.2 to easy-install.pth file

Using /home/kook/envs/oldman-2.7/lib/python2.7/site-packages
Searching for SPARQLWrapper==1.6.4
Best match: SPARQLWrapper 1.6.4
Adding SPARQLWrapper 1.6.4 to easy-install.pth file

Using /home/kook/envs/oldman-2.7/lib/python2.7/site-packages
Searching for rdflib-jsonld==0.2
Best match: rdflib-jsonld 0.2
Adding rdflib-jsonld 0.2 to easy-install.pth file

Using /home/kook/envs/oldman-2.7/lib/python2.7/site-packages
Searching for rdflib==4.2.0.dev0
Best match: rdflib 4.2.0.dev0
rdflib 4.2.0.dev0 is already the active version in easy-install.pth
Installing rdf2dot script to /home/kook/envs/oldman-2.7/bin
Installing csv2rdf script to /home/kook/envs/oldman-2.7/bin
Installing rdfpipe script to /home/kook/envs/oldman-2.7/bin
Installing rdfs2dot script to /home/kook/envs/oldman-2.7/bin
Installing rdfgraphisomorphism script to /home/kook/envs/oldman-2.7/bin

Using /home/kook/envs/oldman-2.7/src/rdflib
Searching for dogpile.core==0.4.1
Best match: dogpile.core 0.4.1
Adding dogpile.core 0.4.1 to easy-install.pth file

Using /home/kook/envs/oldman-2.7/lib/python2.7/site-packages
Searching for html5lib==0.999
Best match: html5lib 0.999
Adding html5lib 0.999 to easy-install.pth file

Using /home/kook/envs/oldman-2.7/lib/python2.7/site-packages
Searching for pyparsing==2.0.3
Best match: pyparsing 2.0.3
Adding pyparsing 2.0.3 to easy-install.pth file

Using /home/kook/envs/oldman-2.7/lib/python2.7/site-packages
Searching for isodate==0.5.1
Best match: isodate 0.5.1
Adding isodate 0.5.1 to easy-install.pth file

Using /home/kook/envs/oldman-2.7/lib/python2.7/site-packages
Searching for six==1.9.0
Best match: six 1.9.0
Adding six 1.9.0 to easy-install.pth file

Using /home/kook/envs/oldman-2.7/lib/python2.7/site-packages
Finished processing dependencies for OldMan==0.2
(oldman-2.7)kook@kook-ThinkPad-R61e:~/envs/oldman-2.7/src/oldman$ ipython
WARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
Python 2.7.8 (default, Oct 20 2014, 15:05:19) 
Type "copyright", "credits" or "license" for more information.

IPython 2.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import oldman
INFO:rdflib:RDFLib Version: 4.2.0-dev
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-962c9add6f3c> in <module>()
----> 1 import oldman

/home/kook/envs/oldman-2.7/src/oldman/build/bdist.linux-x86_64/egg/oldman/__init__.py in <module>()

/home/kook/envs/oldman-2.7/src/oldman/build/bdist.linux-x86_64/egg/oldman/resource/manager.py in <module>()

ImportError: No module named store.selector

In [2]: 
Do you really want to exit ([y]/n)? 
(oldman-2.7)kook@kook-ThinkPad-R61e:~/envs/oldman-2.7/src/oldman$ rm ~/envs/oldman-2.7/local/lib/python2.7/site-packages/OldMan-0.2-py2.7.egg 
(oldman-2.7)kook@kook-ThinkPad-R61e:~/envs/oldman-2.7/src/oldman$ ipython
WARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
Python 2.7.8 (default, Oct 20 2014, 15:05:19) 
Type "copyright", "credits" or "license" for more information.

IPython 2.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import oldman
INFO:rdflib:RDFLib Version: 4.2.0-dev

In [2]: 
Do you really want to exit ([y]/n)? 
(oldman-2.7)kook@kook-ThinkPad-R61e:~/envs/oldman-2.7/src/oldman$ cd examples/
(oldman-2.7)kook@kook-ThinkPad-R61e:~/envs/oldman-2.7/src/oldman/examples$ ipython
WARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
Python 2.7.8 (default, Oct 20 2014, 15:05:19) 
Type "copyright", "credits" or "license" for more information.

IPython 2.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import oldman
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-962c9add6f3c> in <module>()
----> 1 import oldman

ImportError: No module named oldman

In [2]: 
```

**Comment by bcogrel** [comment] 2015-02-21 10:22
Have you try to open `python` instead of `ipython`?
Apparently, `ipython` has not been installed in your virtualenv:

    WARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.

If you prefer IPython, you can try to install it in your virtualenv:

    pip install ipython

**Comment by bcogrel** [comment] 2015-02-21 10:43
I tried to install it on another machine and I have been able to reproduce this problem: 

    ImportError: No module named store.selector

The problem is that the sub-package `oldman.store` was not declared in `setup.py`. Now, it should be fixed.

Thanks again for reporting it!

**Comment by koo5** [comment] 2015-02-21 13:13
:)

**Closed** 2016-01-03 17:06 UTC
